# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

services:

  orderer.sfiot.com:
    container_name: orderer.sfiot.com
    extends:
      file: peer-base.yaml
      service: orderer-base
    volumes:
        - ../channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
        - ../crypto-config/ordererOrganizations/sfiot.com/orderers/orderer.sfiot.com/msp:/var/hyperledger/orderer/msp
        - ../crypto-config/ordererOrganizations/sfiot.com/orderers/orderer.sfiot.com/tls/:/var/hyperledger/orderer/tls
        - orderer.sfiot.com:/var/hyperledger/production/orderer
    ports:
      - 7050:7050

  peer0.org2.sfiot.com:
    container_name: peer0.org2.sfiot.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.org2.sfiot.com
      - CORE_PEER_ADDRESS=peer0.org2.sfiot.com:9051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:9051
      - CORE_PEER_CHAINCODEADDRESS=peer0.org2.sfiot.com:9052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:9052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org2.sfiot.com:9051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.org2.sfiot.com:10051
      - CORE_PEER_LOCALMSPID=Org2MSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/org2.sfiot.com/peers/peer0.org2.sfiot.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/org2.sfiot.com/peers/peer0.org2.sfiot.com/tls:/etc/hyperledger/fabric/tls
        - peer0.org2.sfiot.com:/var/hyperledger/production
    ports:
      - 9051:9051
    extra_hosts:
      - "orderer.sfiot.com:10.1.1.140"
      - "orderer2.sfiot.com:10.1.1.140"
      - "orderer3.sfiot.com:10.1.1.140"

  peer1.org2.sfiot.com:
    container_name: peer1.org2.sfiot.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.org2.sfiot.com
      - CORE_PEER_ADDRESS=peer1.org2.sfiot.com:10051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:10051
      - CORE_PEER_CHAINCODEADDRESS=peer1.org2.sfiot.com:10052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:10052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.org2.sfiot.com:10051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.org2.sfiot.com:9051
      - CORE_PEER_LOCALMSPID=Org2MSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/org2.sfiot.com/peers/peer1.org2.sfiot.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/org2.sfiot.com/peers/peer1.org2.sfiot.com/tls:/etc/hyperledger/fabric/tls
        - peer1.org2.sfiot.com:/var/hyperledger/production
    ports:
      - 10051:10051
    extra_hosts:
      - "orderer.sfiot.com:10.1.1.140"
      - "orderer2.sfiot.com:10.1.1.140"
      - "orderer3.sfiot.com:10.1.1.140"
