# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

volumes:
  peer0.org4.sfiot.com:
  peer1.org4.sfiot.com:

networks:
  byfn:

services:

  peer0.org4.sfiot.com:
    container_name: peer0.org4.sfiot.com
    extends:
      file: base/peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.org4.sfiot.com
      - CORE_PEER_ADDRESS=peer0.org4.sfiot.com:14051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:14051
      - CORE_PEER_CHAINCODEADDRESS=peer0.org4.sfiot.com:14052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:14052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.org4.sfiot.com:15051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org4.sfiot.com:14051
      - CORE_PEER_LOCALMSPID=Org4MSP
    volumes:
        - /var/run/:/host/var/run/
        - ./org4-artifacts/crypto-config/peerOrganizations/org4.sfiot.com/peers/peer0.org4.sfiot.com/msp:/etc/hyperledger/fabric/msp
        - ./org4-artifacts/crypto-config/peerOrganizations/org4.sfiot.com/peers/peer0.org4.sfiot.com/tls:/etc/hyperledger/fabric/tls
        - peer0.org4.sfiot.com:/var/hyperledger/production
    ports:
      - 14051:14051
    networks:
      - byfn

  peer1.org4.sfiot.com:
    container_name: peer1.org4.sfiot.com
    extends:
      file: base/peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.org4.sfiot.com
      - CORE_PEER_ADDRESS=peer1.org4.sfiot.com:15051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:15051
      - CORE_PEER_CHAINCODEADDRESS=peer1.org4.sfiot.com:15052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:15052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.org4.sfiot.com:14051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.org4.sfiot.com:15051
      - CORE_PEER_LOCALMSPID=Org4MSP
    volumes:
        - /var/run/:/host/var/run/
        - ./org4-artifacts/crypto-config/peerOrganizations/org4.sfiot.com/peers/peer1.org4.sfiot.com/msp:/etc/hyperledger/fabric/msp
        - ./org4-artifacts/crypto-config/peerOrganizations/org4.sfiot.com/peers/peer1.org4.sfiot.com/tls:/etc/hyperledger/fabric/tls
        - peer1.org4.sfiot.com:/var/hyperledger/production
    ports:
      - 15051:15051
    networks:
      - byfn


  Org4cli:
    container_name: Org4cli
    image: hyperledger/fabric-tools:$IMAGE_TAG
    tty: true
    stdin_open: true
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - FABRIC_LOGGING_SPEC=INFO
      #- FABRIC_LOGGING_SPEC=DEBUG
      - CORE_PEER_ID=Org4cli
      - CORE_PEER_ADDRESS=peer0.org4.sfiot.com:14051
      - CORE_PEER_LOCALMSPID=Org4MSP
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org4.sfiot.com/peers/peer0.org4.sfiot.com/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org4.sfiot.com/peers/peer0.org4.sfiot.com/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org4.sfiot.com/peers/peer0.org4.sfiot.com/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org4.sfiot.com/users/Admin@org4.sfiot.com/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash
    volumes:
        - /var/run/:/host/var/run/
        - ./../chaincode/:/opt/gopath/src/github.com/chaincode
        - ./org4-artifacts/crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
        - ./crypto-config/peerOrganizations/org1.sfiot.com:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1.sfiot.com
        - ./crypto-config/peerOrganizations/org2.sfiot.com:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org2.sfiot.com
        - ./crypto-config/peerOrganizations/org3.sfiot.com:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org3.sfiot.com
        - ./scripts:/opt/gopath/src/github.com/hyperledger/fabric/peer/scripts/
    depends_on:
      - peer0.org4.sfiot.com
      - peer1.org4.sfiot.com
    networks:
      - byfn
